@startuml
!theme plain

title cup: Deployment

node "Local Computer" as A {
  node "Operating System" as B {

    node "Java Virtual Machine" as C {
      [HelloWorldApp]
    }

  }
}

header
 marco.mangan@pucrs.br
 2023-02-01
 https://docs.oracle.com/javase/tutorial/getStarted/cupojava/unix.html
end header

@enduml
