@startuml

!theme plain

title gs-spring-boot: What you need

package "OS Shell" as A {
  [bash] 
}

package "Transfer Data, Multi-Network Protocol Tool" as Z #Linen {
  [curl] #Linen
}

package "Programming Platform" as B {

  package "JDK 1.8+" {
    package "Java Language"
    package "Java Virtual Machine"
    package "JDK Libraries"
    package "JDK Tools" {
      [javac]
      [java]
      [jar]
    }
  }

}

A -Down[hidden]-> B
D -Down[hidden]-> C

package "Build Automation Tool" as D  {
 [Maven 3.2+]  
 [Gradle 4.0+] #Linen
}

package "IDE" as C {
 artifact [Spring Tool Suite] as STS
 artifact [IntelliJ IDEA] as I
 artifact [VSCode] as VS
 artifact [Another Text editor or IDE] as F
}

header
 marco.mangan@pucrs.br
 2023-01-20
 https://spring.io/guides/gs/spring-boot
end header

@enduml
