@startuml

title AWS Beanstalk

package "Beanstalk Samples Environments" {

  [Docker] as Docker #Orange
  [Multicontainer Docker] as Multi #Tomato
  component "Preconfigured Docker (Glassfish)" <<Jakarta>> #LightYellow

  [Go]

  component "Corretto" <<Jakarta>> #LightGreen
  component "Tomcat"<<Jakarta>> #LightYellow

  [.NET Core on Linux]
  [.NET]

  [Node.js]
  [PHP] as PHP
  [Python] as Python
  [Ruby]

}

header
 marco.mangan@gmail.com
 2023-01-22
 https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/GettingStarted.DeployApp.html
end header
@enduml
