@startuml

header
 marco.mangan@pucrs.br
 2023-01-24
 https://docs.spring.io/spring-boot/docs/current/reference/html/deployment.html
end header

title Deploying Spring Boot Applications

cloud "Cloud Foundry" as Foundry

component Kubernetes as Kubernetes

component Heroku as Heroku

AWS <.up. Heroku

component "Cloud Captain" as Captain

package "Public Cloud Providers" {

  cloud "Amazon Web Services (AWS)" as AWS {

    [AWS Elastic Beanstalk] #LightBlue

  }

  AWS <.Up. Captain
  AWS <.. Kubernetes
  Azure <.. Kubernetes
  Google <.. Kubernetes

  Google <.Up.. Foundry
  AWS <.Up... Foundry
  Azure <.Up.. Foundry

  cloud "Google Cloud" as Google {

    [App Engine]

    [Container Engine]

    [Compute Engine]
  }

  cloud "Azure" as Azure {

    [Azure Spring Cloud]

    [Azure App Service]
  }
}
@enduml
