@startuml

!theme plain

title gs-maven: Classes

class HelloWorldApp {
  {static} main(java.lang.String[] args)
}

package java as C {

  package lang {
    class String

    class System {
      {static} out : java.io.PrintStream
    }

  HelloWorldApp .> System

  }
  package io {
    class PrintStream {
      println(java.lang.String)
    }
  }
}



header
 marco.mangan@gmail.com
 2023-02-01
 https://docs.oracle.com/javase/tutorial/getStarted/cupojava/unix.html
end header


@enduml
